x = [1 2 3 4];
h = [1 1 1 1];
y = conv(x,h);
subplot(2,2,1);
stem(x);
subplot(2,2,2);
stem(h);
n1 = length(x);
n2 = length(h);
n = 1:1:(n1+n2)-1;
subplot(2,2,3); 
stem(n,y);
title('Build in output');
y=findConv(x,h);
subplot(2,2,4);
stem(y);
xlabel('----->n');
ylabel('y[n]');
title('Implemented Convolution of two signal');
